blueprint:
  name: Entity Unavailable Notification
  description: Sends notification of which entity has lost connection
  domain: automation
  input:
    entity_name:
      name: Entity
      description: Device to check
      selector:
        entity: {}
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
  source_url: https://community.home-assistant.io/t/simple-mobile-notification-when-device-becomes-unavailable/255239
mode: queued
max: 10
trigger:
- entity_id: !input 'entity_name'
  for: '30'
  platform: state
  to: unavailable
action:
- device_id: !input 'notify_device'
  domain: mobile_app
  type: notify
  message: '{{ trigger.to_state.name }} disconnected'
