homeassistant:
  name: VHome
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  time_zone: Europe/Kiev
  unit_system: metric
  elevation: 270
  internal_url: "http://rasp.lan:8123"
  customize: !include customize.yaml
  packages: !include_dir_merge_named custom/packages
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# end default configs
recorder: !include custom/recorder.yaml
sensor: !include_dir_merge_list custom/sensors
binary_sensor: !include_dir_merge_list custom/sensors_bin
switch: !include custom/switch.yaml
timer: !include custom/timers.yaml
input_number: !include custom/input/number.yaml
input_boolean: !include custom/input/boolean.yaml
climate: !include custom/climate.yaml

lovelace:
  # mode: yaml
  mode: storage
  # resources:
  #   - url: /hacsfiles/simple-thermostat/simple-thermostat.js
  #     type: module
    # - url: /hacsfiles/scheduler-card/scheduler-card.js
    #   type: module
  #   - url: /hacsfiles/toggle-control-button-row/toggle-control-button-row.js
  #     type: module
  dashboards:
    manual-mode:
      mode: yaml
      title: Manual Dash
      show_in_sidebar: true
      icon: mdi:toolbox
      filename: ui-lovelace.yaml

# influxdb:
#   port: 8086
#   database: has
#   username: has
#   password: has_pwd
#   # max_retries: 3
#   default_measurement: state

mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  username: mqtt
  password: mqtt

mikrotik:
  - name: Mikrotik
    host: 192.168.20.1
    username: !secret mikrotik_user
    password: !secret mikrotik_pass

telegram_bot:
  - platform: polling
    api_key: !secret api_bot_key
    allowed_chat_ids:
      - !secret telegram_id1
      - !secret telegram_id2

notify:
  - name: telegram_id1
    platform: telegram
    chat_id: !secret telegram_id1

  - name: telegram_id2
    platform: telegram
    chat_id: !secret telegram_id2

media_player:
  - platform: mpd
    host: 127.0.0.1

