homeassistant:
  name: VHome
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  time_zone: Europe/Kiev
  unit_system: metric
  elevation: 270
  customize: !include_dir_merge_named all/customize
  internal_url: "http://rasp.lan:8123"

  # Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-thermostat-dark-card/thermostat-dark-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module

frontend:
  # your configuration.
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include all/groups.yaml
timer: !include all/timer.yaml
input_boolean: !include all/input_boolean.yaml
automation: !include_dir_merge_list all/automation
script: !include_dir_merge_list  all/scripts
scene: !include all/scenes.yaml
sensor: !include_dir_merge_list all/sensors
binary_sensor: !include_dir_merge_list all/bin_sensors
recorder: !include all/recorder.yaml

mqtt:
  broker: core-mosquitto  # Локальный брокер
  discovery: true
  discovery_prefix: homeassistant
  username: mqtt
  password: mqtt
