
title: Home Assistant - сервер
views:

  - title: Main
    icon: mdi:home-assistant
    cards:
      # - type: entities
      #   show_header_toggle: false
      #   entities:
      #     - entity: switch.0x00124b00209e96c4_l1
      #     - entity: switch.0x00124b00209e96c4_l2

      # дитяча
      - type: thermostat
        entity: climate.0x5c0272fffed9d5ff
      - type: thermostat
        entity: climate.0x5c0272fffedab255
      # спальня
      - type: thermostat
        entity: climate.0x847127fffe960b38

  - title: Сервер
    icon: mdi:raspberry-pi

    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Текущее состояние**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline

    #     - type: entities
    #       show_header_toggle: false
    #       entities:
    #         - entity: sensor.maria_db_size
    #           name: Объем БД
    #           icon: mdi:database

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Графики**
        - type: horizontal-stack
          cards:
          - type: gauge
            name: Загрузка CPU
            unit: '%'
            entity: sensor.processor_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85
          - type: gauge
            name: Загрузка ОЗУ
            unit: '%'
            entity: sensor.memory_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85

      - type: horizontal-stack
        cards:

          - type: gauge
            name: Диск заполнен
            unit: '%'
            entity: sensor.disk_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85

          - type: gauge
            name: Свободное место
            unit: 'Гб'
            entity: sensor.disk_free
            severity:
              red: 2
              yellow: 6
              green: 8

      - type: history-graph
        entities:
          - entity: sensor.maria_db_size
            name: Maria DB

  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    cards:
        - type: weather-forecast
          entity: weather.home

  - title: СС 2531
    icon: mdi:usb-flash-drive

    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
              **Добавление устройств**
        - type: entities
          title: Добавление Zigbee устройств
          show_header_toggle: false
          entities:
              - entity: input_boolean.zigbee_permit_join
              - entity: timer.zigbee_permit_join
              - entity: sensor.bridge_state
