title: Home Assistant - сервер


views:

  - title: Main
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Вітальня
        entities:
        - entity: sensor.0x5c0272fffec72d04_temperature
          name: Temp
        - entity: sensor.0x5c0272fffec72d04_humidity
          name: Вологість
        - entity: climate.0x5c0272fffedabc57
        - entity: climate.0x5c0272fffedabed2
        - entity: binary_sensor.termo_heat_value_11_1
        - entity: binary_sensor.termo_heat_value_11_2
        - entity: sensor.term_11_1_valve
        - entity: sensor.term_11_2_valve

      - type: entities
        title: Дитяча/Кабінет
        entities:
        - entity: sensor.0x5c0272fffebda093_temperature
          name: Temp
        - entity: sensor.0x5c0272fffebda093_humidity
          name: Вологість
        - entity: climate.0x5c0272fffed9d5ff
        - entity: climate.0x5c0272fffedab255
        - entity: climate.0x847127fffe93ff05
        - entity: binary_sensor.termo_heat_value_22_1
        - entity: binary_sensor.termo_heat_value_22_2
        - entity: binary_sensor.termo_heat_value_22_3
        - entity: sensor.term_22_1_valve
        - entity: sensor.term_22_2_valve
        - entity: sensor.term_22_3_valve

      - type: entities
        title: Спальня
        entities:
        - entity: sensor.0x847127fffe18e757_temperature
          name: Temp
        - entity: sensor.0x847127fffe18e757_humidity
          name: Вологість
        - entity: climate.0x847127fffe960b38
        - entity: climate.0x847127fffe940161
        - entity: binary_sensor.termo_heat_value_21_1
        - entity: binary_sensor.termo_heat_value_21_2
        - entity: sensor.term_21_1_valve
        - entity: sensor.term_21_2_valve

      - type: entities
        title: Кухня
        entities:
          - entity: climate.0x847127fffe9f3342
          - entity: binary_sensor.termo_heat_value_12_1
          - entity: sensor.term_12_1_valve

  - title: Тести
    icon: mdi:flask
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: thermostat
                entity: climate.room_f1_1
                name: Вітальня
              - type: thermostat
                entity: climate.kitchen
                name: Кухня
          - type: horizontal-stack
            cards:
            - type: thermostat
              entity: climate.room_f2_1
              name: Спальня
            - type: thermostat
              entity: climate.room_f2_2
              name: Дитяча/Кабінет

      - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              # - type: history-graph
              #   entities:
              #     - entity: sensor.0x5c0272fffec72d04_temperature
              #       name: Вітальня
              #     - entity: sensor.0x847127fffe18e757_temperature
              #       name: Спальня
              #     - entity: sensor.0x5c0272fffebda093_temperature
              #       name: Дитяча/Кабінет
              #     - entity: sensor.term_12_1_temperature
              #       name: Кухня
              # -----------------
                # - type: entities
                #   entities:
                #     - sensor.0x5c0272fffec72d04_temperature
                #     - sensor.0x847127fffe18e757_temperature
                #     - sensor.0x5c0272fffebda093_temperature
                #     - sensor.term_12_1_temperature
              # -----------------
              - type: sensor
                entity: sensor.0x5c0272fffec72d04_temperature
                name: Вітальня
                graph: line
                detail: 1
                hours_to_show: 24

              - type: sensor
                entity: sensor.0x847127fffe18e757_temperature
                name: Спальня
                graph: line
                detail: 1
                hours_to_show: 24

              - type: sensor
                entity: sensor.0x5c0272fffebda093_temperature
                name: Дитяча/Кабінет
                graph: line
                detail: 1
                hours_to_show: 24

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Вітальня
            cards:
              - type: thermostat
                entity: climate.0x5c0272fffedabc57
              - type: thermostat
                entity: climate.0x5c0272fffedabed2

          - type: horizontal-stack
            title: Спальня
            cards:
              - type: thermostat
                entity: climate.0x847127fffe960b38
              - type: thermostat
                entity: climate.0x847127fffe940161

          - type: horizontal-stack
            title: Дитяча/Кабінет
            cards:
              - type: thermostat
                entity: climate.0x5c0272fffed9d5ff
              - type: thermostat
                entity: climate.0x5c0272fffedab255
              - type: thermostat
                entity: climate.0x847127fffe93ff05

      # - type: sensor
      #   entity: binary_sensor.termo_heat_value_1

  - title: Test2
    icon: mdi:flask-empty-plus
    cards:
      - type: thermostat
        entity: climate.pterm_room_11
        name: Вітальня
      - type: thermostat
        entity: climate.pterm_room_21
        name: Спальня
      - type: thermostat
        entity: climate.pterm_room_22
        name: Дитяча
      - type: entity
        entity: binary_sensor.boiler_is_on
      - type: entity
        entity: switch.complex_boiler

  - title: Scheduler
    icon: mdi:clock-outline
    cards:
      - type: custom:scheduler-card
        # groups:
        #   - name: Climate
        #     icon: mdi:home-thermometer
        include:
          - climate.pterm_room_11
          - climate.pterm_room_21
          - climate.pterm_room_22
        # domains:
        # entities:
        display_options:
          primary_info: "{name}"




  - title: Сервер
    icon: mdi:raspberry-pi
    badges:
      - sensor.processor_temperature
      - sensor.processor_use_percent
    cards:
      # - type: horizontal-stack
      - type: vertical-stack
        cards:
        # - type: markdown
        #   content: >
        #      **Текущее состояние**
        - type: entities
          show_header_toggle: false
          title:  'Текущее состояние'
          entities:
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-outline
            - entity: sensor.last_boot
              name: Last Boot at
              icon: mdi:calendar-check-outline
            - entity: sensor.maria_db_size
              name: DB Size
              icon: mdi:database
            - type: divider
            - type: call-service
              icon: mdi:database-refresh
              name: Compress DB
              action_name: Run
              service: recorder.purge
              service_data:
                keep_days: 7
                repack: true
    #     - type: entities
    #       show_header_toggle: false
    #       entities:
    #         - entity: sensor.maria_db_size
    #           name: Объем БД
    #           icon: mdi:database

      - type: vertical-stack
        cards:
        # - type: markdown
        #   content: >
        #      **Графики**
        - type: horizontal-stack
          cards:
          - type: gauge
            name: Загрузка CPU
            unit: '%'
            entity: sensor.processor_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85
          - type: gauge
            name: Загрузка ОЗУ
            unit: '%'
            entity: sensor.memory_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85

      - type: horizontal-stack
        cards:

          - type: gauge
            name: Диск заполнен
            unit: '%'
            entity: sensor.disk_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85

          - type: gauge
            name: Свободное место
            unit: 'Гб'
            entity: sensor.disk_free
            severity:
              red: 2
              yellow: 6
              green: 8

      - type: vertical-stack
        cards:
          - type: history-graph
            refresh_interval: 1800
            hours_to_show: 48
            entities:
              - entity: sensor.speedtest_download
                name: Download
              - entity: sensor.speedtest_upload
                name: Upload
              - entity: sensor.speedtest_ping
                name: Ping


          - type: history-graph
            entities:
              - entity: sensor.maria_db_size
                name: Maria DB

  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    cards:
        - type: weather-forecast
          entity: weather.home

  - title: Network
    icon: mdi:signal-cellular-2
    cards:
      - type: entities
      # - type: history-graph
        title: Рівень сигналу
        entities:
          - entity: sensor.0x00124b00209e96c4_linkquality

          - entity: sensor.0x5c0272fffedabc57_linkquality
          - entity: sensor.0x5c0272fffedabed2_linkquality
          - entity: sensor.0x847127fffe9f3342_linkquality
          - entity: sensor.0x847127fffe960b38_linkquality
          - entity: sensor.0x847127fffe940161_linkquality
          - entity: sensor.0x5c0272fffed9d5ff_linkquality
          - entity: sensor.0x5c0272fffedab255_linkquality
          - entity: sensor.0x847127fffe93ff05_linkquality

          - entity: sensor.0x5c0272fffec72d04_linkquality
          - entity: sensor.0x847127fffe18e757_linkquality
          - entity: sensor.0x5c0272fffebda093_linkquality


  # - title: СС 2531
  #   icon: mdi:usb-flash-drive

  #   cards:
  #     - type: vertical-stack
  #       cards:
  #       - type: markdown
  #         content: >
  #             **Добавление устройств**
  #       - type: entities
  #         title: Добавление Zigbee устройств
  #         show_header_toggle: false
  #         entities:
  #             - entity: input_boolean.zigbee_permit_join
  #             - entity: timer.zigbee_permit_join
  #             - entity: sensor.bridge_state


      # - type: custom:thermostat-dark-card
      #   title: Дитяча/Кабінет
      #   entity: climate.0x5c0272fffed9d5ff
      #   chevron_size: 100
      #   ambient_temperature: sensor.0x5c0272fffebda093_temperature
        # hvac:
        #   states:
        #     'Off': 'idle'
        #     'Cooling': 'cooling'
        #     'Heating': 'heating'
        #   attribute: operation_mode
