- platform: template
  switches:
    complex_boiler:
      value_template: "{{ states('binary_sensor.boiler_is_on') }}"
      turn_on:
        service: script.boiler_turn_on
      turn_off:
        service: script.boiler_turn_off

    relative_boiler1:
      value_template: "{{ states('binary_sensor.boiler_is_on') }}"
      turn_on:
        service: script.boiler_turn_on
      turn_off:
        service: script.try_to_switch_off_boiler1
    relative_boiler2:
      value_template: "{{ states('binary_sensor.boiler_is_on') }}"
      turn_on:
        service: script.boiler_turn_on
      turn_off:
        service: script.try_to_switch_off_boiler2
    relative_boiler3:
      value_template: "{{ states('binary_sensor.boiler_is_on') }}"
      turn_on:
        service: script.boiler_turn_on
      turn_off:
        service: script.try_to_switch_off_boiler3

