- platform: template
  switches:
    complex_boiler:
      value_template: "{{ states('binary_sensor.boiler_is_on') }}"      
      turn_on:
        service: script.boiler_turn_on
      turn_off:
        service: script.boiler_turn_off

# - platform: pulseaudio_loopback
  # sink_name: alsa_output.platform-bcm2835_audio.analog-stereo
  # source_name: ""
  # name: ""